package sshush

import (
	"fmt"
	"log/slog"
	"os"
	"slices"
	"strings"

	"github.com/k0kubun/pp/v3"
	"github.com/mongodb-forks/go-difflib/difflib"
)

type (
	sshConfigSources []string

	Runner struct {
		Sources     sshConfigSources
		Destination string
	}
)

func (s *Runner) Run(verbose bool, debug bool, dryRun bool, version string) error {
	if verbose {
		slog.Info(
			"sshush v"+version+" running with",
			"sources", s.Sources,
			"destination", s.Destination,
		)
	}

	p := Parser{
		Verbose: verbose,
		Debug:   debug,
		DryRun:  dryRun,
	}

	err := p.Load(&s.Sources)
	if err != nil {
		return fmt.Errorf("loading sources: %w", err)
	}

	headers := []string{
		"# Generated by sshush v" + version,
		"# From " + strings.Join(s.Sources, ", "),
		"",
	}

	output, err := p.ProduceConfig()
	if err != nil {
		return fmt.Errorf("producing config: %w", err)
	}

	if debug {
		pp.Println("Global config: ", p.GlobalConfig)
		pp.Println("Default config: ", p.DefaultConfig)
		pp.Println("Extensions: ", p.Extensions)
	}

	output = removeTrailingEmptyLine(output)
	newConfig := slices.Concat(headers, output)

	if dryRun {
		c, err := os.ReadFile(s.Destination)
		if err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("reading destination file: %w", err)
		}
		oldConfig := ""
		if !os.IsNotExist(err) {
			lines := strings.Split(string(c), "\n")
			oldConfig = strings.Join(removeTrailingEmptyLine(lines), "\n")
		}

		diff, err := PrettyDiff(oldConfig, strings.Join(newConfig, "\n"), s.Destination)
		if err != nil {
			return fmt.Errorf("creating diff: %w", err)
		}
		fmt.Println(diff)
	} else {
		fh, err := os.Create(s.Destination)
		if err != nil {
			return fmt.Errorf("opening destination file: %w", err)
		}
		defer fh.Close()

		n, err := writeLines(fh, newConfig)
		if err != nil {
			return fmt.Errorf("writing output: %w", err)
		}

		if verbose {
			slog.Info(fmt.Sprintf("Wrote %d bytes to %s", n, s.Destination))
		}
	}

	return nil
}

// PrettyDiff compares two strings and returns a colored diff.
func PrettyDiff(old, new, file string) (string, error) {
	diff := difflib.LineDiffParams{
		A:        difflib.SplitLines(old),
		B:        difflib.SplitLines(new),
		FromFile: fmt.Sprintf("%s (Old)", file),
		ToFile:   fmt.Sprintf("%s (New)", file),
		Context:  3,
		Colored:  true,
	}
	return difflib.GetUnifiedDiffString(diff)
}

// writeLines writes a map of lines to the file handle.
// It returns the number of bytes written and an error, if any.
func writeLines(fh *os.File, lines []string) (int, error) {
	n := 0
	for _, line := range lines {
		nL, err := writeLine(fh, line)
		if err != nil {
			return n, err
		}
		n += nL
	}
	return n, nil
}

// writeLine writes a line to the file handle.
// It returns the number of bytes written and an error, if any.
func writeLine(fh *os.File, line string) (int, error) {
	n, err := fh.WriteString(line + "\n")
	if err != nil {
		return n, fmt.Errorf("writing line: %w", err)
	}

	return n, nil
}

// removeTrailingEmptyLine removes the last empty line from the output.
// There's already a trailing newline so this prevents double new lines.
func removeTrailingEmptyLine(output []string) []string {
	length := len(output)

	if length >= 1 && output[length-1] == "" {
		output = output[:length-1]
	}

	return output
}
