package sshush

import (
	"fmt"
	"log/slog"
	"os"
	"slices"
	"strings"

	"github.com/k0kubun/pp/v3"
	"github.com/sergi/go-diff/diffmatchpatch"
)

type (
	sshConfigSources []string

	Runner struct {
		Sources     sshConfigSources
		Destination string
	}
)

func (s *Runner) Run(verbose bool, debug bool, dryRun bool, version string) error {
	if verbose {
		slog.Info(
			"sshush v"+version+" running with",
			"sources", s.Sources,
			"destination", s.Destination,
		)
	}

	p := Parser{
		Verbose: verbose,
		Debug:   debug,
		DryRun:  dryRun,
	}

	err := p.Load(&s.Sources)
	if err != nil {
		return fmt.Errorf("loading sources: %w", err)
	}

	headers := []string{
		"# Generated by sshush v" + version,
		"# From " + strings.Join(s.Sources, ", "),
		"",
	}

	output, err := p.ProduceConfig()
	if err != nil {
		return fmt.Errorf("producing config: %w", err)
	}

	if debug {
		pp.Println("Global config: ", p.GlobalConfig)
		pp.Println("Default config: ", p.DefaultConfig)
		pp.Println("Extensions: ", p.Extensions)
	}

	output = removeTrailingEmptyLine(output)
	newConfig := slices.Concat(headers, output)

	config := ""
	if dryRun {
		c, err := os.ReadFile(s.Destination)
		if err != nil {
			return fmt.Errorf("reading destination file: %w", err)
		}
		lines := strings.Split(string(c), "\n")
		config = strings.Join(removeTrailingEmptyLine(lines), "\n")

		fmt.Println(PrettyFileDiff(config, strings.Join(newConfig, "\n"), verbose))
	} else {
		fh, err := os.Create(s.Destination)
		if err != nil {
			return fmt.Errorf("opening destination file: %w", err)
		}
		defer fh.Close()

		n, err := writeLines(fh, newConfig)
		if err != nil {
			return fmt.Errorf("writing output: %w", err)
		}

		if verbose {
			slog.Info(fmt.Sprintf("Wrote %d bytes to %s", n, s.Destination))
		}
	}

	return nil
}

// PrettyFileDiff takes the content of two files and returns the pretty diff
func PrettyFileDiff(s1, s2 string, verbose bool) string {
	dmp := diffmatchpatch.New()
	wSrc, wDst, warray := dmp.DiffLinesToRunes(s1, s2)
	diffs := dmp.DiffMainRunes(wSrc, wDst, false)
	diffs = dmp.DiffCharsToLines(diffs, warray)
	var newDiffs []diffmatchpatch.Diff
	if verbose {
		newDiffs = diffs
	} else {
		// only select different lines to limit output
		for _, item := range diffs {
			if item.Type != diffmatchpatch.DiffEqual {
				newDiffs = append(newDiffs, item)
			}
		}
	}

	if len(newDiffs) > 1 {
		return dmp.DiffPrettyText(newDiffs)
	} else {
		return ""
	}
}

// writeLines writes a map of lines to the file handle.
// It returns the number of bytes written and an error, if any.
func writeLines(fh *os.File, lines []string) (int, error) {
	n := 0
	for _, line := range lines {
		nL, err := writeLine(fh, line)
		if err != nil {
			return n, err
		}
		n += nL
	}
	return n, nil
}

// writeLine writes a line to the file handle.
// It returns the number of bytes written and an error, if any.
func writeLine(fh *os.File, line string) (int, error) {
	n, err := fh.WriteString(line + "\n")
	if err != nil {
		return n, fmt.Errorf("writing line: %w", err)
	}

	return n, nil
}

// removeTrailingEmptyLine removes the last empty line from the output.
// There's already a trailing newline so this prevents double new lines.
func removeTrailingEmptyLine(output []string) []string {
	length := len(output)

	if length >= 1 && output[length-1] == "" {
		output = output[:length-1]
	}

	return output
}
